[package]
name = "{{project-name}}"
authors = ["{{author}}"]
license = "{{license}}"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
strip = true
lto=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
